# Generated by Django 4.2.6 on 2023-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_time',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, verbose_name='Product Desc'),
            preserve_default=False,
        ),
    ]
