# Generated by Django 4.2.6 on 2023-10-29 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_data_time_product_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=254, verbose_name='Char')),
            ],
            options={
                'verbose_name': 'AddChar',
                'verbose_name_plural': 'AddChar',
            },
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.addchar')),
            ],
            options={
                'verbose_name': 'Additional Information',
                'verbose_name_plural': 'Additional Information',
            },
        ),
    ]
