# Generated by Django 4.2.6 on 2023-10-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_additionalinformation_char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Review')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
