# Generated by Django 4.2.6 on 2023-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_reviewfor_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereview',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time'),
        ),
    ]
