# Generated by Django 4.2.6 on 2023-10-30 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0028_alter_subcategory_subcat"),
    ]

    operations = []
