# Generated by Django 4.2.6 on 2023-10-30 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0029_auto_20231030_1931"),
    ]

    operations = []
